[package]
name = "stego_encryptor"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
clap = { version = "4.0", features = ["derive"] }
aes-gcm = "0.10"
pbkdf2 = "0.12"
rand = "0.8"
sha2 = "0.10"
anyhow = "1.0"