[package]
name = "stego_encryptor"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
hmac = "0.12"
sha3 = "0.10"